### ISSUE TITLE
[FYI] GPU support now in datashader

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuDataShader#2]
DataShader now has GPU support and should eventually supersede cuDataShdaer: [init GPU support DataShader](https://github.com/pyviz/datashader/pull/793)

cuDataShader will be used for more experimental work.

**Comment by jakirkham** [comment]
This is now part of `datashader` version `0.9.0`.

**Comment by jbednar** [comment]
Just to be clear, GPU support is now part of Datashader, but no code from cuDataShader was used to build that support.  cuDataShader was certainly inspirational, though!

**Comment by jakirkham** [comment]
Yep sorry for the vague comment. Thanks for clarifying things 🙂
